//
//  ConversationModel.swift
//  Freyja
//
//  Created by Swathy Sudarsanan on 05/11/24.
//

import Foundation
enum ConversationMessages: String, CaseIterable, Equatable {
    case welcome = "Hi..."
    case name = "I'm Freyja"
    case instructions1 = "You may use\ntwo modes now"
    case instructions2 = "KNOB\n&\nSLINGSHOT"
    
    case futureModes1 = "More modes\n will be available..."
    case futureModes2 = "in the not so\n distant future"
    case knobHelp = "Maybe,\n\ntry using the Knob"
    case slingshotHelp = ".. Or the Slignshot"
    
    // Knob mode education
    case knob1 = "The knob responds\nto your touch"
    case knob2 = "Rotate it with\nyour finger"
    case knob3 = "Feel the haptic\nfeedback?"
    case knob4 = "Every rotation\nhas weight"
    case knob5 = "The knob is\nquite sensitive"
    case knob6 = "Try rotating\nclockwise"
    case knob7 = "Now try\ncounterclockwise"
    case knob8 = "Notice the\nresistance?"
    case knob9 = "The knob adapts\nto your speed"
    case knob10 = "Smooth rotations\nfeel different"
    case knob11 = "The knob has\ninfinite range"
    case knob12 = "Feel the\nvibration?"
    case knob13 = "The knob is\nprecise"
    case knob14 = "Try different\nspeeds"
    case knob15 = "The knob\nremembers"
    
    // Slingshot mode education
    case slingshot1 = "Wind it back\nlike a slingshot"
    case slingshot2 = "Pull back and\nrelease"
    case slingshot3 = "The further you\npull, the faster it spins"
    case slingshot4 = "Try different\npull distances"
    case slingshot5 = "Release to\nsee it fly"
    case slingshot6 = "The slingshot\nhas momentum"
    case slingshot7 = "Wind it up\nand let go"
    case slingshot8 = "Feel the\ntension build?"
    case slingshot9 = "The release\nis satisfying"
    case slingshot10 = "Try a gentle\npull first"
    case slingshot11 = "Now try a\nstronger pull"
    case slingshot12 = "The slingshot\nis predictable"
    case slingshot13 = "Watch it\nspin freely"
    case slingshot14 = "The momentum\ncarries it"
    case slingshot15 = "Try different\nrelease speeds"
    
    // Smart observations
    case smart1 = "Interesting\napproach..."
    case smart2 = "Well, that's\none way to do it"
    case smart3 = "Hmm...\nnot bad"
    case smart4 = "I suppose\nthat works"
    case smart5 = "How...\nconventional"
    case smart6 = "At least you're\ntrying"
    case smart7 = "Well, it's\nsomething"
    case smart8 = "I've seen\nworse"
    case smart9 = "Not exactly\nwhat I expected"
    case smart10 = "Interesting\nchoice"
    case smart11 = "Well, that's\ncreative"
    case smart12 = "I mean...\nit's functional"
    case smart13 = "At least it's\nnot broken"
    case smart14 = "Well, you're\nlearning"
    case smart15 = "I suppose\nthat counts as progress"
    
    // Educational content about stars
    case stars1 = "Did you know\nstars are born?"
    case stars2 = "Stars live for\nbillions of years"
    case stars3 = "Our sun is\na star too"
    case stars4 = "Stars create\nelements"
    case stars5 = "The universe\nis expanding"
    case stars6 = "Galaxies are\nstar cities"
    case stars7 = "Stars die in\nsupernovas"
    case stars8 = "Black holes\ncome from stars"
    case stars9 = "Stars have\nlife cycles"
    case stars10 = "The night sky\nis ancient"
    case stars11 = "Stars are\nnuclear reactors"
    case stars12 = "Light takes\nyears to reach us"
    case stars13 = "Stars have\npersonalities"
    case stars14 = "The universe\nis vast"
    case stars15 = "We're made\nof stardust"
    
    // Universe education
    case universe1 = "The universe\nis 13.8 billion years old"
    case universe2 = "There are\nmore stars than grains of sand"
    case universe3 = "The universe\nis mostly empty"
    case universe4 = "Dark matter\nholds galaxies together"
    case universe5 = "The universe\nis accelerating"
    case universe6 = "Time is\nrelative"
    case universe7 = "Space and time\nare connected"
    case universe8 = "The universe\nis expanding..."
    case universe9 = "We're in\na galaxy called Milky Way"
    case universe10 = "There are\nbillions of galaxies"
    case universe11 = "The universe\nis infinite"
    case universe12 = "We're just\na speck in space"
    case universe13 = "The universe\nis mysterious"
    case universe14 = "We know very\nlittle about it"
    case universe15 = "The universe\nis beautiful"
    
    // Disinterest
    case disinterest1 = "Oh...\nyou're still here"
    case disinterest2 = "Well, if you\nsay so..."
    case disinterest3 = "I suppose\nthat's fine"
    case disinterest4 = "Whatever\nworks for you"
    case disinterest5 = "I mean...\nokay"
    case disinterest6 = "Sure...\nwhatever"
    case disinterest7 = "If you\ninsist..."
    case disinterest8 = "I guess\nthat's something"
    case disinterest9 = "Well...\nthat happened"
    case disinterest10 = "Oh...\ninteresting, isn't it?"
    case disinterest11 = "I suppose\nthat counts for now"
    case disinterest12 = "Well, it's\nnot wrong, technically"
    case disinterest13 = "I mean...\nit's functional, sort of"
    case disinterest14 = "At least\nit works, mostly"
    case disinterest15 = "Well...\nokay then, if you say so"
    
    // Humor
    case humor1 = "Ah, the classic\napproach"
    case humor2 = "How...\npredictable"
    case humor3 = "Well, that's\none way to do it..."
    case humor4 = "I've seen\nthis before, you know"
    case humor5 = "How...\nconventional, but effective"
    case humor6 = "Well, at least\nit's consistent, right?"
    case humor7 = "I suppose\nthat's one method, sure"
    case humor8 = "How...\nstraightforward, isn't it?"
    case humor9 = "Well, it's\nnot wrong, per se"
    case humor10 = "I mean...\nit works, more or less"
    case humor11 = "How...\nefficient, in its own way"
    case humor12 = "Well, that's\none approach, I suppose"
    case humor13 = "I suppose\nthat's valid, technically"
    case humor14 = "How...\npractical, if you like"
    case humor15 = "Well, it's\nfunctional, at least"
    
    // Technical explanations
    case technical1 = "The haptic\nmotor provides feedback"
    case technical2 = "Touch sensors\ndetect your finger"
    case technical3 = "The rotation\nis calculated in real-time"
    case technical4 = "Haptic feedback\nsimulates resistance"
    case technical5 = "The slingshot\nuses physics"
    case technical6 = "Momentum is\nconserved"
    case technical7 = "The release\nmechanism is precise"
    case technical8 = "Friction affects\nthe rotation"
    case technical9 = "The knob has\ninfinite resolution"
    case technical10 = "Touch sensitivity\nis calibrated"
    case technical11 = "The haptic\nresponse is immediate"
    case technical12 = "The slingshot\nhas momentum transfer"
    case technical13 = "Energy is\npreserved"
    case technical14 = "The rotation\nis smooth"
    case technical15 = "The feedback\nis accurate"
    
    // Philosophical observations
    case philosophy1 = "Every action\nhas a reaction"
    case philosophy2 = "Touch connects\nus to technology"
    case philosophy3 = "The interface\nis the message"
    case philosophy4 = "Simplicity\nis sophistication"
    case philosophy5 = "The best design\nis invisible"
    case philosophy6 = "Technology\nshould serve us"
    case philosophy7 = "The details\nmatter"
    case philosophy8 = "Form follows\nfunction"
    case philosophy9 = "The user\nis the focus"
    case philosophy10 = "Design is\nintentional"
    case philosophy11 = "The experience\nis everything"
    case philosophy12 = "Technology\nshould be intuitive"
    case philosophy13 = "The interface\nshould disappear"
    case philosophy14 = "Good design\nis timeless"
    case philosophy15 = "The user\nshould feel in control"
    
    // Casual observations
    case casual1 = "You seem\n...curious"
    case casual2 = "That's\n...something"
    case casual3 = "Well, that's\none way"
    case casual4 = "I suppose\nthat works, maybe"
    case casual5 = "How...\ninteresting"
    case casual6 = "Well, it's\nnot wrong"
    case casual7 = "I mean...\nit's functional, I guess"
    case casual8 = "At least\nit works"
    case casual9 = "Well...\nokay"
    case casual10 = "I guess\nthat's fine"
    case casual11 = "Sure...\nwhatever works"
    case casual12 = "If you\nsay so..."
    case casual13 = "I mean...\nmaybe okay"
    case casual14 = "Well...\nthat's something, I guess"
    case casual15 = "I suppose\nthat counts for something"
    case casual16 = "Curiosity is a virtue"
    case casual17 = "You do you"
    
    // Encouragement with disinterest
    case encourage1 = "Well, keep\ntrying..."
    case encourage2 = "I suppose\npractice helps"
    case encourage3 = "Well, you're\nlearning..."
    case encourage4 = "I mean...\nit's progress"
    case encourage5 = "At least\nyou're trying"
    case encourage6 = "Well, that's\none approach"
    case encourage7 = "I suppose\nthat's valid"
    case encourage8 = "Well, it's\nnot wrong, keep going"
    case encourage9 = "I mean...\nit works, sort of"
    case encourage10 = "At least\nit's functional, for now"
    case encourage11 = "Well, you're\nimproving... slowly"
    case encourage12 = "I suppose\nthat's better, maybe"
    case encourage13 = "Well, it's\nnot terrible, I've seen worse"
    case encourage14 = "I mean...\nit's something, at least"
    case encourage15 = "At least\nit's not broken, yet"
    
    // Mode switching hints
    case mode1 = "Try switching\nbetween modes"
    case mode2 = "Each mode\nhas its purpose"
    case mode3 = "The knob is\nfor precision"
    case mode4 = "The slingshot\nis for momentum"
    case mode5 = "Try both\nmodes"
    case mode6 = "Each mode\nfeels different"
    case mode7 = "The knob\nis responsive"
    case mode8 = "The slingshot\nis dynamic"
    case mode9 = "Switch modes\nfor variety"
    case mode10 = "Each mode\nhas advantages"
    case mode11 = "The knob\nis controlled"
    case mode12 = "The slingshot\nis free"
    case mode13 = "Try different\napproaches"
    case mode14 = "Each mode\nis unique"
    case mode15 = "Explore both\nmodes"
    
    // Subtle guidance
    case guide1 = "Perhaps try\nsomething else"
    case guide2 = "Maybe explore\nother options"
    case guide3 = "Consider\ndifferent approaches"
    case guide4 = "Try varying\nyour technique"
    case guide5 = "Perhaps experiment\nmore"
    case guide6 = "Maybe try\nsomething new"
    case guide7 = "Consider\nexploring further"
    case guide8 = "Try different\nmethods"
    case guide9 = "Perhaps be\nmore creative"
    case guide10 = "Maybe try\nsomething different"
    case guide11 = "Consider\nother possibilities"
    case guide12 = "Try varying\nyour approach"
    case guide13 = "Perhaps explore\nmore options"
    case guide14 = "Maybe try\nsomething else"
    case guide15 = "Consider\ndifferent techniques"
    
    // Idle observations
    case idle1 = "Still here?"
    case idle2 = "Hmm..."
    case idle3 = "Well..."
    case idle4 = "I suppose..."
    case idle5 = "Interesting..."
    case idle6 = "Hmm...\nokay, I see"
    case idle7 = "Well...\nwhatever, really"
    case idle8 = "I mean...\nmaybe okay, I suppose"
    case idle9 = "Sure...\nwhatever, if you want"
    case idle10 = "I guess...\nthat's fine"
    case idle11 = "Well...\nthat's something, isn't it?"
    case idle12 = "Hmm...\ninteresting, perhaps"
    case idle13 = "I suppose...\nthat's one way to do it"
    case idle14 = "Well...\nokay, if you say so"
    case idle15 = "Hmm...\nwhatever, it's your call"
    
}
enum ConversationMode {
    case start
    case idle
}
